# language: php
 
# php:
#   - 5.4
#   - 5.5
#   - 5.6
#   - hhvm

# before_script:
#   - composer self-update
#   - composer install --prefer-source --no-interaction --dev

# script: phpunit -c test/KalkulatorTest.php

# matrix:
#   allow_failures:
#     - php: 5.6
#     - php: hhvm
#   fast_finish: true

# notifications:
#   on_success: always
#   on_failure: always

language: php

php: 5.4

script: phpunit test/LongLatConverterTest.php

matrix:
  allow_failures:
    php: 5.4
  fast_finish: true